<!doctype html>
<html lang="en">
  <script>
    // if(localStorage.getItem('connexion') != "true")
    //   window.location.replace("../");
    // else
    //   setTimeout(()=>localStorage.removeItem('connexion'),60000);
  </script>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css">
    <?php foreach($this->styles as $style): ?>
        <link rel="stylesheet" href="/public/css/<?= $style ?>.css">
    <?php endforeach; ?>
    
    <title>Administration</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="../assets/css/style.css">
  </head>
  <body>
    
<header class="navbar navbar-dark sticky-top bg-secondary flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6" href="/"><img src="../../assets/imgs/logo.png" style="height: 75px;" class="img-logo" alt="Sunitronics Technology" ></a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <input class="form-control form-control-dark w-100 rounded-0 border-0" type="text" placeholder="Search" aria-label="Search">
  <div class="navbar-nav">
    <div class="nav-item text-nowrap">
      <a class="nav-link px-3 leave" href="#">Déconnexion</a>
    </div>
  </div>
  
</header>

<div class="container-fluid">
  <div class="row">
    <?php include VIEW_DIR."/sideNav.phtml"; ?>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <div class="alert d-none my-2 alert-primary" role="alert">
        </div>
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Dashboard</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
         
            </div>
        </div>
        <?php include VIEW_DIR."/modal.phtml"; ?>
        
        <div class="root">
          <?php include VIEW_DIR."/home.phtml"; ?>
        </div>
    </main>
  </div>
</div>
<?php foreach($this->scripts as $script): ?>
                <script type="module" src="../../plugins/<?= $script ?>.js"></script>
<?php endforeach; ?>
<script src="../../assets/vendors/jquery/jquery-3.4.1.js"></script>
<script src="../assets/js/main.js" type="module"></script>
<script src="../../plugins/php-stripe/public/assets/js/main.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>  </body>
<div class="plugin-script">

</div>
</html>
